# Generated by Django 2.0.7 on 2018-07-19 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('invested', models.FloatField()),
                ('fees_usd', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('a', 'Active'), ('i', 'Inactive')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('trade_type', models.CharField(choices=[('b', 'Buy'), ('s', 'Sell')], max_length=2)),
                ('amount', models.FloatField()),
                ('fees_usd', models.FloatField()),
                ('avg_price', models.FloatField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas_dash.Stock')),
            ],
        ),
    ]
