# Generated by Django 2.0.7 on 2018-08-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_dash', '0002_auto_20180720_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='fees_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='invested',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
